# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

# Rack related gems
gem 'rack', '~> 2.2.4'
gem 'rackup', '~> 0.1.0'

# web servers
gem 'puma', '~> 5.6.5'
gem 'thin', '~> 1.8.1'
gem 'webrick', '~> 1.7.0'

# extras
gem 'activesupport', '~> 7.0.4'
